const data = {
	products: [
		{
			_id: "1",
			name: "Nike Slim Shirt",
			category: "Shirts",
			image: "/images/product-1.jpg",
			price: 120,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "high quality shirt.",
		},
		{
			_id: "2",
			name: "Adidas Fit Shirt",
			category: "Shirts",
			image: "/images/product-2.jpg",
			price: 100,
			brand: "Adidas",
			rating: 4.0,
			numReviews: 10,
			description: "high quality shirt.",
		},
		{
			_id: "3",
			name: "Lacoste Free Shirt",
			category: "Shirts",
			image: "/images/product-3.jpg",
			price: 220,
			brand: "Lacoste",
			rating: 4.0,
			numReviews: 17,
			description: "high quality shirt.",
		},
		{
			_id: "4",
			name: "Champion Slim Pant",
			category: "Pants",
			image: "/images/product-4.jpg",
			price: 70,
			brand: "Champion",
			rating: 4.5,
			numReviews: 14,
			description: "high quality shirt.",
		},
		{
			_id: "5",
			name: "Puma Slim Pant",
			category: "Pants",
			image: "/images/product-5.jpg",
			price: 165,
			brand: "Puma",
			rating: 4.5,
			numReviews: 10,
			description: "high quality shirt.",
		},
		{
			_id: "6",
			name: "Adidas Fit Pant",
			category: "Pants",
			image: "/images/product-6.jpg",
			price: 120,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			description: "high quality shirt.",
		},
		{
			_id: "7",
			name: "Lacoste Casual Shirt",
			category: "Shirt",
			image: "/images/p1.jpg",
			price: 120,
			brand: "Lacoste",
			rating: 4.5,
			numReviews: 10,
			description: "high quality shirt.",
		},
	],
};

export default data;
